Repository Vegitime/Vegitime, pull requests merged in 2022-11, with the labels that each got.

#5 MyFarm페이지 마크업 및 스타일링
  .gitignore
  public/assets/carrot.png
  public/assets/eggplant.png
  public/assets/onion.png
  src/assets/alarm.svg
  src/assets/alarmlist.svg
  src/assets/cart.svg
  src/assets/home.svg
  src/assets/logout.svg
  src/assets/mic.svg
  src/assets/money.svg
  src/assets/user.svg
  src/main.tsx
  src/pages/MyFarm/components/Header.tsx
  src/pages/MyFarm/components/LinkVegiInfo.tsx
  src/pages/MyFarm/components/MoneyInfo.tsx
  src/pages/MyFarm/components/Navigation.tsx
  src/pages/MyFarm/components/Title.tsx
  src/pages/MyFarm/components/index.ts
  src/pages/MyFarm/index.tsx
  src/pages/index.ts
  webpack/common.js
Labels: 스타일, 기능 개발, 에셋

#8 Alarm List 페이지 마크업 및 스타일링
  src/assets/eggplant.svg
  src/assets/remove.svg
  src/pages/AlarmList/components/AlarmList.tsx
  src/pages/AlarmList/index.tsx
  src/pages/VegiPage/components/ProgressBar.tsx
  src/pages/VegiPage/components/Time.tsx
  src/pages/VegiPage/components/Title.tsx
  src/pages/VegiPage/components/VegiImage.tsx
  src/pages/VegiPage/components/index.ts
  src/pages/VegiPage/index.tsx
Labels: 스타일, 기능 개발, 에셋

#12 전역 스타일 spacing 수정
  src/styles/GlobalStyle.ts
Labels: 스타일

#18 Alarm List 및 채소 페이지 스타일링 리펙토링 완료
  src/pages/AlarmList/components/AlarmList.tsx
  src/pages/VegiPage/components/ProgressBar.tsx
  src/pages/VegiPage/components/Time.tsx
  src/pages/VegiPage/components/Title.tsx
Labels: 스타일, 리팩토링

#21 SettingAlarm페이지 마크업 구현
  src/main.tsx
  src/pages/SettingAlarm/components/Header.tsx
  src/pages/SettingAlarm/components/MoneyInfo.tsx
  src/pages/SettingAlarm/components/Navigation.tsx
  src/pages/SettingAlarm/components/TimePicker.tsx
  src/pages/SettingAlarm/components/Title.tsx
  src/pages/SettingAlarm/components/index.ts
  src/pages/SettingAlarm/index.tsx
  src/pages/index.ts
Labels: 기능 개발
