Repository Vegitime/Vegitime, pull requests merged in 2023-03, with the labels that each got.

#127 fix: 에러 메세지 중복 현상 수정
  client/src/pages/SignIn/index.tsx
Labels: 버그 수정

#128 chore: 배포 폴더 gitignore 추가
  .gitignore
Labels: 배포, 환경 설정

#129 fix: 알람시간 zero padding 처리
  client/src/utils/executeFuncOnTime.ts
  client/src/utils/getDefaultAlarmFormat.ts
Labels: 버그 수정

#130 fix: node-schedule의 timezone을 UTC로 수정
  server/index.js
  server/routes/vegetables.js
Labels: 배포, 버그 수정

#131 fix: 에러 메세지 중복 현상 수정(웹팩)
  client/src/pages/SignIn/index.tsx
Labels: 버그 수정
