Repository Vegitime/Vegitime, pull requests merged in 2023-01, with the labels that each got.

#26 feat: 페이지간 라우터 연결, chore: asset에 일러스트 추가
  client/src/assets/avocado01.svg
  client/src/assets/avocado02.svg
  client/src/assets/avocado03.svg
  client/src/assets/avocado04.svg
  client/src/assets/avocado05.svg
  client/src/assets/carrot01.svg
  client/src/assets/carrot02.svg
  client/src/assets/carrot03.svg
  client/src/assets/carrot04.svg
  client/src/assets/carrot05.svg
  client/src/assets/eggplant01.svg
  client/src/assets/eggplant02.svg
  client/src/assets/eggplant03.svg
  client/src/assets/eggplant04.svg
  client/src/assets/eggplant05.svg
  client/src/assets/onion01.svg
  client/src/assets/onion02.svg
  client/src/assets/onion03.svg
  client/src/assets/onion04.svg
  client/src/assets/onion05.svg
  client/src/assets/radish01.svg
  client/src/assets/radish02.svg
  client/src/assets/radish03.svg
  client/src/assets/radish04.svg
  client/src/assets/radish05.svg
  client/src/assets/tomato01.svg
  client/src/assets/tomato02.svg
  client/src/assets/tomato03.svg
  client/src/assets/tomato04.svg
  client/src/assets/tomato05.svg
  client/src/main.tsx
  client/src/pages/AlarmList/components/AlarmList.tsx
  client/src/pages/Market/components/Header.tsx
  client/src/pages/Market/components/Navigation.tsx
  client/src/pages/MyFarm/components/Header.tsx
  client/src/pages/MyFarm/components/Navigation.tsx
  client/src/pages/MyPage/components/Header.tsx
  client/src/pages/MyPage/components/Navigation.tsx
  client/src/pages/SettingAlarm/components/Header.tsx
  client/src/pages/SettingAlarm/components/Navigation.tsx
  client/src/pages/SettingAlarm/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/components/SignForm.tsx
  client/src/pages/SignUp/components/SignTip.tsx
  client/src/pages/StartPage/index.tsx
Labels: 기능 개발

#28 컴포넌트 리팩토링
  client/src/components/Header.tsx
  client/src/components/MoneyInfo.tsx
  client/src/components/Navigation.tsx
  client/src/components/Title.tsx
  client/src/components/index.ts
  client/src/pages/AlarmList/index.tsx
  client/src/pages/Market/components/ButtonVegiInfo.tsx
  client/src/pages/Market/components/Header.tsx
  client/src/pages/Market/components/Title.tsx
  client/src/pages/Market/components/index.ts
  client/src/pages/Market/index.tsx
  client/src/pages/MyFarm/components/Header.tsx
  client/src/pages/MyFarm/components/MoneyInfo.tsx
  client/src/pages/MyFarm/components/Navigation.tsx
  client/src/pages/MyFarm/components/Title.tsx
  client/src/pages/MyFarm/components/index.ts
  client/src/pages/MyFarm/index.tsx
  client/src/pages/MyPage/components/Header.tsx
  client/src/pages/MyPage/components/MoneyInfo.tsx
  client/src/pages/MyPage/components/Navigation.tsx
  client/src/pages/MyPage/components/Title.tsx
  client/src/pages/MyPage/components/index.ts
  client/src/pages/MyPage/index.tsx
  client/src/pages/SettingAlarm/components/Header.tsx
  client/src/pages/SettingAlarm/components/MoneyInfo.tsx
  client/src/pages/SettingAlarm/components/Navigation.tsx
  client/src/pages/SettingAlarm/components/Title.tsx
  client/src/pages/SettingAlarm/components/index.ts
  client/src/pages/SettingAlarm/index.tsx
  client/src/pages/VegiPage/index.tsx
  client/src/styles/GlobalStyle.ts
Labels: 기능 개발, 리팩토링

#32 MyPage 완성
  client/public/assets/alarm.png
  client/public/assets/alarmlist.png
  client/public/assets/arrow.svg
  client/public/assets/cart.png
  client/public/assets/cart.svg
  client/public/assets/close.png
  client/public/assets/close.svg
  client/public/assets/delete.png
  client/public/assets/home.png
  client/public/assets/home.svg
  client/public/assets/id.png
  client/public/assets/logout.png
  client/public/assets/logout.svg
  client/public/assets/mic.png
  client/public/assets/mic.svg
  client/public/assets/money.svg
  client/public/assets/moneybag.png
  client/public/assets/nickname.png
  client/public/assets/password.png
  client/public/assets/user.png
  client/public/assets/user.svg
  client/src/assets/alarm.svg
  client/src/assets/alarmlist.svg
  client/src/assets/home.svg
  client/src/components/Header.tsx
  client/src/components/MoneyInfo.tsx
  client/src/components/Navigation.tsx
  client/src/pages/Market/components/ButtonVegiInfo.tsx
  client/src/pages/Market/components/ModalDialog.tsx
  client/src/pages/Market/components/MoneyInfo.tsx
  client/src/pages/Market/components/index.ts
  client/src/pages/MyPage/index.tsx
  client/src/utils/index.ts
  client/src/utils/makeChart.ts
Labels: 기능 개발, 리팩토링, 에셋

#31 AlarmList, VegiPage 컴포넌트 리팩토링
  client/public/assets/avocado01.svg
  client/public/assets/avocado02.svg
  client/public/assets/avocado03.svg
  client/public/assets/avocado04.svg
  client/public/assets/avocado05.svg
  client/public/assets/carrot01.svg
  client/public/assets/carrot02.svg
  client/public/assets/carrot03.svg
  client/public/assets/carrot04.svg
  client/public/assets/carrot05.svg
  client/public/assets/eggplant01.svg
  client/public/assets/eggplant02.svg
  client/public/assets/eggplant03.svg
  client/public/assets/eggplant04.svg
  client/public/assets/eggplant05.svg
  client/public/assets/onion01.svg
  client/public/assets/onion02.svg
  client/public/assets/onion03.svg
  client/public/assets/onion04.svg
  client/public/assets/onion05.svg
  client/public/assets/radish01.svg
  client/public/assets/radish02.svg
  client/public/assets/radish03.svg
  client/public/assets/radish04.svg
  client/public/assets/radish05.svg
  client/public/assets/setting.svg
  client/public/assets/tomato01.svg
  client/public/assets/tomato02.svg
  client/public/assets/tomato03.svg
  client/public/assets/tomato04.svg
  client/public/assets/tomato05.svg
  client/src/pages/AlarmList/components/AlarmList.tsx
  client/src/pages/AlarmList/index.tsx
  client/src/pages/SignUp/components/SignForm.tsx
  client/src/pages/VegiPage/components/ActionButton.tsx
  client/src/pages/VegiPage/components/ProgressBar.tsx
  client/src/pages/VegiPage/components/Time.tsx
  client/src/pages/VegiPage/components/Title.tsx
  client/src/pages/VegiPage/components/index.ts
  client/src/pages/VegiPage/index.tsx
Labels: 리팩토링, 에셋

#33 Market페이지 내부 컴포넌트 리팩토링 및 완성
  client/src/main.tsx
  client/src/pages/Market/components/ButtonVegiInfo.tsx
  client/src/pages/Market/components/ModalDialog.tsx
  client/src/pages/Market/components/TextButton.tsx
  client/src/pages/Market/index.tsx
Labels: 리팩토링

#35 Modal 컴포넌트 구현
  client/public/assets/carrot.svg
  client/public/assets/eggplant.svg
  client/public/assets/nav_background_img_vegi.png
  client/public/assets/onion.svg
  client/public/index.html
  client/src/components/Header.tsx
  client/src/components/IconButton.tsx
  client/src/components/ModalDialog.tsx
  client/src/components/MoneyInfo.tsx
  client/src/components/Navigation.tsx
  client/src/components/TextButton.tsx
  client/src/components/index.ts
  client/src/main.tsx
  client/src/pages/AlarmList/components/AlarmList.tsx
  client/src/pages/Market/components/ButtonVegiInfo.tsx
  client/src/pages/Market/components/ModalDialog.tsx
  client/src/pages/Market/components/index.ts
  client/src/pages/Market/index.tsx
  client/src/pages/MyFarm/components/LinkVegiInfo.tsx
  client/src/pages/MyFarm/components/index.ts
  client/src/pages/MyFarm/index.tsx
  client/src/pages/SettingAlarm/index.tsx
  client/src/pages/VegiPage/components/Time.tsx
  client/src/pages/VegiPage/components/Title.tsx
  client/src/pages/VegiPage/components/index.ts
  client/src/pages/VegiPage/index.tsx
  client/src/pages/index.ts
  client/src/styles/GlobalStyle.ts
  client/src/utils/constants.ts
  client/src/utils/index.ts
  client/src/utils/makeChart.ts
  server/mock/users.js
Labels: 기능 개발, 리팩토링, 버그 수정

#38 feat: 서버 기본 설정 in server/index.js
  server/index.js
Labels: 기능 개발

#41 ScrollToTop컴포넌트 구현
  client/src/App.tsx
  client/src/components/ScrollToTop.tsx
  client/src/components/index.ts
  client/src/main.tsx
Labels: 기능 개발

#40 user 스키마 생성 및 auth 미들웨어 설정
  server/middleware/auth.js
  server/models/User.js
  server/utils/generateResponse.js
Labels: 기능 개발

#44 Develop
  client/src/pages/SettingAlarm/components/TimePicker.tsx
  client/src/pages/SettingAlarm/index.tsx
  client/src/styles/GlobalStyle.ts
Labels: 기능 개발

#47 VegiSelect 컴포넌트 구현
  client/src/assets/polygon.svg
  client/src/pages/SettingAlarm/components/TimePicker.tsx
  client/src/pages/SettingAlarm/components/VegiSelect.tsx
  client/src/pages/SettingAlarm/components/index.ts
Labels: 기능 개발, 리팩토링

#43 feat: user API 생성
  server/index.js
  server/routes/users.js
Labels: 기능 개발

#52 SettingAlarm 페이지 구현 및 전체 페이지 mock데이터 기반 렌더링 구현
  client/src/App.tsx
  client/src/assets/polygon.svg
  client/src/components/Header.tsx
  client/src/components/TextButton.tsx
  client/src/pages/AlarmList/components/AlarmList.tsx
  client/src/pages/AlarmList/index.tsx
  client/src/pages/Market/index.tsx
  client/src/pages/SettingAlarm/components/TimePicker.tsx
  client/src/pages/SettingAlarm/components/VegiSelect.tsx
  client/src/pages/SettingAlarm/index.tsx
  client/src/pages/VegiPage/components/Time.tsx
  client/src/pages/VegiPage/index.tsx
  client/src/utils/getDefaultAlarmFormat.ts
  client/src/utils/index.ts
  server/mock/users.js
Labels: 기능 개발, 리팩토링

#51 음성인식 기능 구현
  client/package-lock.json
  client/package.json
  client/public/assets/micoff.svg
  client/public/assets/micon.svg
  client/src/pages/VegiPage/components/ActionButton.tsx
  client/src/pages/VegiPage/components/DictButton.tsx
  client/src/pages/VegiPage/components/index.ts
  client/src/pages/VegiPage/index.tsx
Labels: 기능 개발, 에셋, 환경 설정

#55 SettingAlarm페이지 url 파라미터 변경 시 재렌더링 구현
  client/src/components/Header.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/SettingAlarm/components/TimePicker.tsx
  client/src/pages/SettingAlarm/components/VegiSelect.tsx
  client/src/pages/SettingAlarm/index.tsx
  client/src/pages/VegiPage/index.tsx
  client/src/utils/constants.ts
Labels: 기능 개발, 리팩토링, 버그 수정

#50 feat: Vegetable, Shop 스키마 생성
  server/models/Shop.js
  server/models/Vegetable.js
Labels: 기능 개발

#57 fix: User, Vegetable 스키마 수정
  server/models/User.js
  server/models/Vegetable.js
Labels: 버그 수정

#59 유저 정보 받아오는 api 생성 및 유틸함수 수정
  server/routes/users.js
  server/utils/generateResponse.js
Labels: 기능 개발

#61 feat: shop api 생성
  server/routes/shop.js
Labels: 기능 개발

#63 vegetabls api 생성 및 적용
  server/index.js
  server/package.json
  server/routes/vegetables.js
Labels: 기능 개발

#54 VegiPage 기능 구현
  client/src/pages/VegiPage/components/DictButton.tsx
  client/src/pages/VegiPage/components/ProgressBar.tsx
  client/src/pages/VegiPage/components/VegiImage.tsx
  client/src/pages/VegiPage/components/index.ts
  client/src/pages/VegiPage/index.tsx
Labels: 기능 개발

#65 api 리팩토링 및 버그 수정
  server/models/Vegetable.js
  server/routes/shop.js
  server/routes/users.js
  server/routes/vegetables.js
Labels: 리팩토링, 버그 수정

#67 VegiPage 자잘한 수정 사항 및 공통 컴포넌트 수정
  client/public/assets/avocado01.svg
  client/public/assets/avocado02.svg
  client/public/assets/avocado03.svg
  client/public/assets/avocado04.svg
  client/public/assets/avocado05.svg
  client/public/assets/carrot01.svg
  client/public/assets/carrot02.svg
  client/public/assets/carrot03.svg
  client/public/assets/carrot04.svg
  client/public/assets/carrot05.svg
  client/public/assets/eggplant01.svg
  client/public/assets/eggplant02.svg
  client/public/assets/eggplant03.svg
  client/public/assets/eggplant04.svg
  client/public/assets/eggplant05.svg
  client/public/assets/onion01.svg
  client/public/assets/onion02.svg
  client/public/assets/onion03.svg
  client/public/assets/onion04.svg
  client/public/assets/onion05.svg
  client/public/assets/radish01.svg
  client/public/assets/radish02.svg
  client/public/assets/radish03.svg
  client/public/assets/radish04.svg
  client/public/assets/radish05.svg
  client/public/assets/tomato01.svg
  client/public/assets/tomato02.svg
  client/public/assets/tomato03.svg
  client/public/assets/tomato04.svg
  client/public/assets/tomato05.svg
  client/src/components/Header.tsx
  client/src/pages/AlarmList/components/AlarmList.tsx
  client/src/pages/Market/components/ButtonVegiInfo.tsx
  client/src/pages/VegiPage/components/DictButton.tsx
  client/src/pages/VegiPage/index.tsx
Labels: 기능 개발, 리팩토링, 에셋

#69 감정에 따른 캐릭터 성장 기능 구현
  client/src/pages/VegiPage/components/DictButton.tsx
  server/mock/praise.js
Labels: 기능 개발

#71 feat: auth 라우팅 구현
  client/src/App.tsx
  client/src/hoc/auth.tsx
  server/routes/users.js
Labels: 기능 개발

#73 SignTip, FooterImg 컴포넌트 경로 변경 및 적용
  client/src/components/FooterImg.tsx
  client/src/components/Navigation.tsx
  client/src/components/SignTip.tsx
  client/src/components/index.ts
  client/src/pages/StartPage/components/index.ts
  client/src/pages/StartPage/index.tsx
Labels: 기능 개발

#75 fix: TextButton 컴포넌트 수정
  client/src/components/TextButton.tsx
Labels: 기능 개발, 버그 수정

#76 usrForm 훅 구현
  client/src/hooks/index.ts
  client/src/hooks/useForm.ts
Labels: 기능 개발

#78 feat: Form 컴포넌트 구현
  client/src/components/Form.tsx
  client/src/components/index.ts
  client/src/pages/SignUp/components/SignForm.tsx
Labels: 기능 개발

#81 feat: InputContainer 컴포넌트 구현
  client/src/components/InputContainer.tsx
  client/src/components/index.ts
  client/src/pages/SignUp/components/SignInputContainer.tsx
Labels: 기능 개발

#83 feat: Input 컴포넌트 구현
  client/src/components/Input.tsx
  client/src/components/index.ts
Labels: 기능 개발

#87 feat: DuplicationButton 컴포넌트 구현
  client/src/pages/SignUp/components/DuplicationButton.tsx
  client/src/pages/SignUp/components/index.ts
Labels: 기능 개발

#89 feat: Signin 페이지 구현
  client/src/pages/SignIn/components/index.ts
  client/src/pages/SignIn/index.tsx
Labels: 기능 개발

#91 SignUP 페이지 구현, axios 설치
  client/package.json
  client/src/pages/SignUp/index.tsx
Labels: 기능 개발, 환경 설정

#93 feat: logout api 적용
  client/src/components/Header.tsx
Labels: 기능 개발

#97 server API 연결
  client/package-lock.json
  client/src/components/Header.tsx
  client/src/pages/AlarmList/components/AlarmList.tsx
  client/src/pages/AlarmList/index.tsx
  client/src/pages/Market/components/ButtonVegiInfo.tsx
  client/src/pages/Market/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/SettingAlarm/components/TimePicker.tsx
  client/src/pages/SettingAlarm/components/VegiSelect.tsx
  client/src/pages/SettingAlarm/index.tsx
  client/src/pages/VegiPage/components/DictButton.tsx
  client/src/pages/VegiPage/index.tsx
  client/src/utils/getDefaultAlarmFormat.ts
  client/src/utils/makeChart.ts
  server/.eslintrc.js
  server/.prettierrc.js
  server/index.js
  server/middleware/auth.js
  server/mock/auth.js
  server/mock/praise.js
  server/mock/users.js
  server/models/Shop.js
  server/models/User.js
  server/models/Vegetable.js
  server/package-lock.json
  server/package.json
  server/routes/shop.js
  server/routes/users.js
  server/routes/vegetables.js
Labels: 스타일, 기능 개발, 환경 설정

#95 Logo 이미지, favicon 적용
  client/public/assets/logo.png
  client/public/assets/vegi_favicon.png
  client/public/assets/vegi_logo.png
  client/public/index.html
  client/src/pages/StartPage/index.tsx
Labels: 리팩토링, 에셋

#99 부자연스러운 동작 수정 및 타입 오류 해결
  client/src/components/Header.tsx
  client/src/components/InputContainer.tsx
  client/src/components/ModalDialog.tsx
  client/src/components/MoneyInfo.tsx
  client/src/components/Navigation.tsx
  client/src/components/SignTip.tsx
  client/src/components/Title.tsx
  client/src/pages/AlarmList/components/LinkVegi.tsx
  client/src/pages/AlarmList/components/index.ts
  client/src/pages/AlarmList/index.tsx
  client/src/pages/Market/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/SettingAlarm/components/VegiSelect.tsx
  client/src/pages/SettingAlarm/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
  client/src/pages/StartPage/index.tsx
  client/src/pages/VegiPage/components/DictButton.tsx
  client/src/pages/VegiPage/components/ProgressBar.tsx
  client/src/pages/VegiPage/index.tsx
  client/src/utils/getDefaultAlarmFormat.ts
  client/src/utils/makeChart.ts
Labels: 스타일, 기능 개발, 리팩토링, 버그 수정

#102 fix: 중복확인 초기화 버그 수정
  client/src/hooks/useForm.ts
  client/src/pages/SignUp/index.tsx
Labels: 버그 수정

#104 DictButton 컴포넌트 disabled 기능 추가 및 버그 수정
  client/src/pages/VegiPage/components/DictButton.tsx
Labels: 기능 개발, 버그 수정

#106 지정한 시간에 함수를 실행시킬 수 있는 유틸함수 구현
  client/src/utils/executeFuncOnTime.ts
  client/src/utils/getDefaultAlarmFormat.ts
  client/src/utils/index.ts
Labels: 기능 개발

#108 오늘 칭찬 완료한 vegetable인지 구분하는 기능 구현
  server/index.js
  server/models/Vegetable.js
  server/package.json
  server/routes/vegetables.js
Labels: 기능 개발

#110 feat: vegi 페이지 설정한 시간에 칭찬 버튼 활성화 기능 구현
  client/src/pages/VegiPage/components/DictButton.tsx
  client/src/pages/VegiPage/index.tsx
Labels: 기능 개발

#114 Build 테스트 환경 구축 및 서비스워커 등록
  client/package-lock.json
  client/package.json
  client/src/main.tsx
  client/webpack/prod.js
  server/index.js
Labels: 기능 개발, 환경 설정
