Repository Vegitime/Vegitime, pull requests merged in 2023-02, with the labels that each got.

#116 전반적인 레이아웃 수정 및 배포
  .gitignore
  client/public/index.html
  client/src/components/FooterImg.tsx
  client/src/components/Header.tsx
  client/src/components/Main.tsx
  client/src/components/Navigation.tsx
  client/src/components/Title.tsx
  client/src/components/index.ts
  client/src/main.tsx
  client/src/pages/AlarmList/components/LinkVegi.tsx
  client/src/pages/AlarmList/index.tsx
  client/src/pages/Market/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/SettingAlarm/index.tsx
  client/src/pages/StartPage/index.tsx
  client/src/pages/VegiPage/components/ProgressBar.tsx
  client/src/pages/VegiPage/components/Time.tsx
  client/src/pages/VegiPage/index.tsx
  client/src/styles/GlobalStyle.ts
  client/webpack/prod.js
  server/app.yaml
  server/index.js
  server/package.json
Labels: 기능 개발, 환경 설정, 버그 수정

#117 로그인, 회원가입 레이아웃 수정
  client/src/components/Form.tsx
  client/src/components/Input.tsx
  client/src/components/InputContainer.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
Labels: 스타일

#118 chore: Create CRA for PWA
  .browserslistrc
  .eslintignore
  .eslintrc.cjs
  .prettierignore
  .prettierrc.cjs
  .vscode/settings.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/service-worker.ts
  client/src/serviceWorkerRegistration.ts
  client/src/setupTests.ts
  client/tsconfig.json
  package-lock.json
  package.json
  public/assets/logo.svg
  public/index.html
  src/assets/logo.svg
  src/components/index.js
  src/main.tsx
  tsconfig.json
  types/assets.d.ts
  webpack/common.js
  webpack/dev.js
  webpack/loaders/assets.js
  webpack/loaders/index.js
  webpack/loaders/svgAssets.js
  webpack/loaders/typescript.js
  webpack/plugins/createBundleAnalyzer.js
  webpack/plugins/createCleanup.js
  webpack/plugins/createCopyAssets.js
  webpack/plugins/createDotEnv.js
  webpack/plugins/createHtmlTemplate.js
  webpack/plugins/createImageMinify.js
  webpack/plugins/createJsMinify.js
  webpack/plugins/index.js
  webpack/prod.js
  webpack/server.js
Labels: 환경 설정

#119 chore: Create server
  server/.eslintrc.js
  server/.prettierrc.js
  server/app.yaml
  server/index.js
  server/middleware/auth.js
  server/models/Shop.js
  server/models/User.js
  server/models/Vegetable.js
  server/package-lock.json
  server/package.json
  server/routes/shop.js
  server/routes/users.js
  server/routes/vegetables.js
  server/utils/generateResponse.js
Labels: 환경 설정

#123 Develop cra
  client/src/service-worker.ts
  server/index.js
  server/package.json
  server/routes/vegetables.js
Labels: 기능 개발, 환경 설정

#124 feat: register service-worker and subscribe
  client/src/pages/SettingAlarm/index.tsx
Labels: 기능 개발

#125 fix: Fix URL to REACT_APP_URL and ASSET_PAHT to REACT_APP_ASSET_PATH in process.env
  client/src/components/FooterImg.tsx
  client/src/components/Form.tsx
  client/src/components/Header.tsx
  client/src/hoc/auth.tsx
  client/src/pages/AlarmList/index.tsx
  client/src/pages/Market/index.tsx
  client/src/pages/MyPage/index.tsx
  client/src/pages/SignIn/index.tsx
  client/src/pages/SignUp/index.tsx
  client/src/pages/VegiPage/components/DictButton.tsx
  client/src/pages/VegiPage/index.tsx
  client/src/utils/getAssetPath.ts
Labels: 버그 수정
